### ISSUE TITLE
Solution soundness issue on datatype formula

### ISSUE THREAD

**Issue by rainoftime** [ultimate-pa/smtinterpol#119]
Hi, for the following formula,
smtinterpol
d208e93 yields `sat`, but z3 and cvc4 return unsat
~~~~
(set-logic ALL)
(set-info :status unsat)
(declare-datatype Color ( ( red ) ( green ) ( blue ) ))

(declare-fun a () Color)
(declare-fun b () Color)
(declare-fun c () Color)
(declare-fun d () Color)

(assert (or (distinct a b c d)
 (< (match a ((red 5) (green 3) (blue 2))) 0)
 (< (match b ((red 2) (x 1))) 0)
 ))

(check-sat)
~~~~

**Comment by jhoenicke** [comment]
Since there is no code for data type support yet, MatchTerms are just treated as uninterpreted symbols, which is, of course, unsound.  There should be an exception that is thrown when a MatchTerm is given to `addTermAxioms`.

**Comment by jhoenicke** [comment]
This should be fixed now that datatypes are supported
