### ISSUE TITLE
NullPointerException in Interpolator.colorTermsInAssertions

### ISSUE THREAD

**Issue by kfriedberger** [ultimate-pa/smtinterpol#126]
With version 881e8631 of SMTInterpol, we get a NullPointerException for the interpolation query from [smtquery.006-c.smt2.txt](https://github.com/ultimate-pa/smtinterpol/files/6647820/smtquery.006-c.smt2.txt).

#### Commandline on a fresh compiled SMTInterpol (runtime about 60s):
`java -ea -jar dist/smtinterpol-2.5-823-g881e8631.jar smtquery.006-c.smt2`

#### Stacktrace:
```
java.lang.NullPointerException
  at de.uni_freiburg.informatik.ultimate.smtinterpol.interpolate.Interpolator.colorTermsInAssertions(Interpolator.java:603)
  at de.uni_freiburg.informatik.ultimate.smtinterpol.interpolate.Interpolator.getInterpolants(Interpolator.java:220)
  at de.uni_freiburg.informatik.ultimate.smtinterpol.smtlib2.SMTInterpol.getInterpolants(SMTInterpol.java:876)
  at de.uni_freiburg.informatik.ultimate.logic.NoopScript.getInterpolants(NoopScript.java:392)
  [...]
```

#### Related:
The same query [smtquery.006-c.smt2.txt](https://github.com/ultimate-pa/smtinterpol/files/6647820/smtquery.006-c.smt2.txt) causes an AssertionError (see [CPAchecker#890](https://gitlab.com/sosy-lab/software/cpachecker/-/issues/890)) in the older version `2.5-732-gd208e931` of SMTInterpol, which is used in CPAchecker. If assertions are disabled, the interpolation query seems to work (I did not check whether the answer (`true`) is actually correct).

**Comment by tanjaschindler** [comment]
The problem was that input terms that were rewritten during preprocessing, e.g., f(x+1+2) to f(x+3), were not correctly assigned to their input partition. Commits 47f2297 and 0b6676a solve this problem by using the partitions of the sub-terms and function symbols to determine the term's partition.
