### ISSUE TITLE
Logics.ALL does not include string theory

### ISSUE THREAD

**Issue by serras** [ultimate-pa/smtinterpol#129]
The [definition of `Logics.ALL`](https://github.com/ultimate-pa/smtinterpol/blob/master/Library-SMTLIB/src/de/uni_freiburg/informatik/ultimate/logic/Logics.java#L27) does not include `Features.S`. This means there's no way to use the string theory in combination with the rest of theories. Is this intended? Would it be possible to get a new constructor which includes it?

**Comment by jhoenicke** [comment]
ALL should include all theories (even those not supported by SMTInterpol itself).  So I will change the definition to include strings.

**Comment by serras** [comment]
Thanks for the quick fix! Do you happen to have an estimate of when a new release may appear in the Maven repository? That would make my life much easier than setting up my own repo! :)

**Comment by jhoenicke** [comment]
I uploaded a new release to the Maven repository.

**Comment by serras** [comment]
Maybe this is asking too much, but would it be possible to also update the Ivy repo at https://www.sosy-lab.org/ivy/de.uni-freiburg.informatik.ultimate/smtinterpol/?

**Comment by jhoenicke** [comment]
Not sure how this works, but it looks like it updated automatically :)
