### ISSUE TITLE
Missing right parenthesis in get-value response

### ISSUE THREAD

**Issue by daniel-larraz** [ultimate-pa/smtinterpol#138]
Running SMTInterpol on:
```
(set-logic QF_LIA)
(declare-fun x () Int)
(declare-fun y () Int)
(check-sat)
(get-value (x y))
```
returns:
```
success
success
success
sat
((x 0)
 (y 0)
```
Notice the missing right parenthesis in the `get-value` response

**Comment by jhoenicke** [comment]
That was an easy fix.   Please let me know, if you need a binary release.

**Comment by daniel-larraz** [comment]
> That was an easy fix. Please let me know, if you need a binary release.

No need. Building with `ant` works fine. Thank you for the quick responses.
