### ISSUE TITLE
ERROR - The proof did not yield a contradiction

### ISSUE THREAD

**Issue by rodrigo7491** [ultimate-pa/smtinterpol#148]
For the attached file (see [test.zip](https://github.com/user-attachments/files/15847882/test.zip)) SMTInterpol produces a proof that is classified as invalid when given to its checker. The output of the check is as below.
```
WARN - Could not find pivot + (or (exists ((x!3 Int)) (and (not (<= (+ x!3 1) 0)) (not (<= (+ (* (- 1) x!3) 1) 0)))) (= A 1)) in [+ (exists ((x!3 Int)) (and (not (<= (+ x!3 1) 0)) (not (<= (+ (* (- 1) x!3) 1) 0)))), + (= A 1)]
ERROR - The proof did not yield a contradiction but [+ (exists ((x!3 Int)) (and (not (<= (+ x!3 1) 0)) (not (<= (+ (* (- 1) x!3) 1) 0)))), + (= A 1)]
invalid
```

Solver command: `java -jar smtinterpol-2.5-1256-g55d6ba76.jar test.smt2`
Checker command: `java -cp smtinterpol-2.5-1256-g55d6ba76.jar de.uni_freiburg.informatik.ultimate.smtinterpol.proof.checker.Main test.smt2 test.proof`

I am using `smtinterpol-2.5-1256-g55d6ba76` on Linux Mint 21.2.

**Comment by jhoenicke** [comment]
Thanks for the report.  The proof is only slightly wrong: the statement is true and removing a single wrong resolution step fixes the problem.  There is a problem with the proof of an instantiation clause.  I have to investigate further.

It has something to do with the intermediate proof representation of instantiation lemmas and the fact that we sometimes creates auxiliary literals for `(or ...)` terms.   In this proof a lemma should proof the unit clause with the literal `(or A B)`, but the proof simplifier assumes that it should proof the clause A,B instead.

The latest master should fix this problem.
