### ISSUE TITLE
Do not abort immediately for interpolation queries with theory of arrays

### ISSUE THREAD

**Issue by PhilippWendler** [ultimate-pa/smtinterpol#22]
Commit 656452f (the merge of branch logger) has introduced [three lines in `SMTInterpol.java`](https://github.com/ultimate-pa/smtinterpol/blob/656452f/SMTInterpol/src/de/uni_freiburg/informatik/ultimate/smtinterpol/smtlib2/SMTInterpol.java#L769) that let all interpolation queries fail immediately if the theory has arrays enabled. Previously SMTInterpol at least attempted to interpolate. It would be great if the previous behavior could be restored, because we simply always set the most general theory, and thus often have interpolation queries without any arrays, but the theory has arrays enabled.

**Comment by PhilippWendler** [comment]
Thanks!

What is your policy about Maven Central uploads? Would you be willing to upload new versions repeatedly (e.g., now a new one with this fix) such that we only need to rely on the versions on Maven, or do you expect to upload new versions only rarely (@cheshire might be interested in this question, too).

**Comment by jhoenicke** [comment]
I wanted to merge the javacup changes first and then do a new release.  I think it is best to release often and then fix the bugs when they are reported.  I'm not sure yet, if snapshot or release is the right mechanism for this.

**Comment by PhilippWendler** [comment]
Great, thanks!
