### ISSUE TITLE
Interface request: expose values contained in a model

### ISSUE THREAD

**Issue by cheshire** [ultimate-pa/smtinterpol#26]
Hi,

It is often convenient to be able to loop over a model, while SMTInterpol only provides an interface for evaluating terms over it.
Would it be possible to expose the interface to see which functions are defined in a model?
From what I see in the source code, it would be sufficient to simply expose (perhaps in an unmodifiable way) the `mFuncVals` value in the `Model` class.

**Comment by jhoenicke** [comment]
Should I add a function that returns `mFuncVals.keys()`?  That would give you the set of FunctionSymbols in the Model.

I wanted to add `Term getFunctionDefinition(String func, TermVariable[] args)` in `Model`, that would return the term that can be used in a `define-fun` command.  Using the set of `FunctionSymbol`s, it would then be easy to enumerate over the functions and then get their definition.

**Comment by cheshire** [comment]
> Should I add a function that returns mFuncVals.keys()? That would give you the set of FunctionSymbols in the Model.

Yes, I think that would be sufficient for our purposes. Thanks!

**Comment by jhoenicke** [comment]
See https://github.com/ultimate-pa/smtinterpol/commit/4c543a594fcec0b5219112527af3a5981e75051c

**Comment by kfriedberger** [comment]
Hi, 
I am currently working on getting the previously mentioned methods () integrated into our project.
For normal symbols and arrays the changes from 4c543a5 seem to work very well, just the UFs cause problems. Is there a convenient way to iterate over the assignments of an uninterpreted function, without knowing its exact arguments?
The class `FunctionValue` seems to be invisible and thus we cannot use the method `getFunctionValue(FunctionSymbol).values()` from our code. It looks like this method could return the necessary information, right?
Do you have any suggestions for this?

**Comment by kfriedberger** [comment]
Hi,
I am currently working on getting the previously mentioned methods () integrated into our project.
For normal symbols and arrays the changes from 4c543a5 seem to work very well, just the UFs cause problems. Is there a convenient way to iterate over the assignments of an uninterpreted function, without knowing its exact arguments?
It is possible to return an ITE-like term where we could extract the assignments, similar to the SMTlib-formatted String when printing the model. Therefore we have to use fresh variables for parameters and depend on a nice ITE-like structure. Fresh variables can be a problem someone uses the same name for something else. Could you provide an API for simply iterating over the assignments or return a Map of assignments?
The class FunctionValue seems to be invisible and thus we cannot use the method getFunctionValue(FunctionSymbol).values() from our code. It looks like this method could return the necessary information, right? Do you have any suggestions for this?
Best,
Karlheinz

**Comment by jhoenicke** [comment]
@kfriedberger  Would it be enough for you, if we make `FunctionValue` public?  Then you can cast the model to `….smtinterpol.model.Model` to access `getFunctionValue`.

We don't guarantee to keep the interface stable, though. Especially, if we handle new theories in the future where a simple case-by-case function definition is not enough.

**Comment by kfriedberger** [comment]
@jhoenicke 
Yes, it would help, if `FunctionValue` and its nested class `Index` would be public visible.
With this simple change, our code should work fine.

We know that such special cases need to be updated whenever the underlying code changes.
However, it might be more convenient for a user to simply iterate over all possible assignments than asking the model and parsing the result. 

(A more difficult solution would be that you provide a method for iterating over all assignments of an uninterperted function directly, evaluating lazily to avoid heavy ressource consumption. But that might be over-engineering.)

More complex theories might cause more complex models. We will handle this when needed.
Btw, when are you planning to support BV-theory? :-)
