### ISSUE TITLE
Simple solving with assumptions sends SMTInterpol into a loop

### ISSUE THREAD

**Issue by cheshire** [ultimate-pa/smtinterpol#27]
The bug is encountered on the following file (though, naturally, we go through the API)

```
(set-option :global-declarations true)
(set-option :random-seed 42)
(set-option :produce-interpolants true)
(set-option :produce-models true)
(set-option :produce-unsat-cores true)
(set-logic QF_AUFLIRA)
(get-option :random-seed)
(push 1)
(pop 1)
(pop 0)
(push 1)
(check-sat-assuming ())
(pop 1)
(pop 0)
(declare-fun v1 () Int)
(declare-fun v2 () Int)
(declare-fun suffix1 () Bool)
(declare-fun suffix2 () Bool)
(declare-fun suffix3 () Bool)
(get-option :random-seed)
(push 1)
(push 1)
(assert (! (or (and (= v1 1) (not (= v1 v2))) suffix1) :named term_0))
(push 1)
(assert (! (or (= v2 1) suffix2) :named term_1))
(push 1)
(assert (! (or (not (= v1 1)) suffix3) :named term_2))
(check-sat-assuming ((not suffix1) (not suffix2) suffix3))
```

**Comment by jhoenicke** [comment]
As I see it, there are two bugs in smtinterpol

1. `(check-sat-assuming ())` is valid syntax, but not supported.  This is trivial to fix (replace a `Term+` by `Term*`)
2. The infinite backtracking loop.  It looks like the whole assumption thing is still buggy.  This will take more time to resolve, sorry.

I would conclude that unfortunately `check-sat-assuming` is not usable at the moment.  I think some fundamental things need to be reworked in this code.

I could try a quick workaround and translate `check-sat-assuming` as `assert` + `check-sat` without any special support for assumption literals.

**Comment by jhoenicke** [comment]
This problem is fixed now.  Hopefully I didn't introduce new bugs, please test.  The version 2.5-7 and beyond have the changes.  So far I only uploaded to the website, do you need a Maven Central release?

**Comment by kfriedberger** [comment]
An official Maven release would be nice. Thanks.

**Comment by kfriedberger** [comment]
@jhoenicke Could you please upload the latest release of SMTInterpol to MavenCentral? Thanks.

**Comment by jhoenicke** [comment]
Updated smtinterpol on MavenCentral to 2.5-12

**Comment by kfriedberger** [comment]
Seems to work. Closing #27 .
