### ISSUE TITLE
NullPointerException after 'check-sat-assuming'

### ISSUE THREAD

**Issue by kfriedberger** [ultimate-pa/smtinterpol#35]
The following snippet causes a NullPointerEception in SMTInterpol 2.5-13.

> (set-logic QF_LIA)
> (declare-fun A () Bool)
> (check-sat-assuming (A))
> (assert (not A))
> (check-sat)

**Comment by kfriedberger** [comment]
There is another, perhaps related problem. The following snippet throws an assertion.

> SMTInterpol env = new SMTInterpol(new DefaultLogger(), () -> false);
> env.setLogic(Logics.QF_AUFLIRA);
> env.declareFun("a", new Sort[] {}, env.getTheory().getBooleanSort());
> Term a = env.term("a");
> LBool sat1 = env.checkSatAssuming(new Term[] {a});
> assert sat1 == LBool.SAT;
> env.assertTerm(env.term("not", a));
> LBool sat2 = env.checkSatAssuming(new Term[] {a}); // <-- assertion is thrown from here
> assert sat2 == LBool.UNSAT;

Stacktrace:
> Exception in thread "main" java.lang.AssertionError: Not an assumption in unsat clause
> at de.uni_freiburg.informatik.ultimate.smtinterpol.dpll.DPLLEngine.checkValidUnsatClause(DPLLEngine.java:1934)
> at de.uni_freiburg.informatik.ultimate.smtinterpol.dpll.DPLLEngine.assume(DPLLEngine.java:1908)
> at de.uni_freiburg.informatik.ultimate.smtinterpol.smtlib2.SMTInterpol.checkSatAssuming(SMTInterpol.java:492)

**Comment by kfriedberger** [comment]
@jhoenicke Any news for this bug?

**Comment by jhoenicke** [comment]
I have fixed part of this, but there are still bugs especially when adding proofs.

**Comment by kfriedberger** [comment]
@jhoenicke Could you upload the new version for Maven? 
We will report further bugs, if we notice them :-)

**Comment by kfriedberger** [comment]
@jhoenicke Could you upload the new version for Maven?
Any news on this?

**Comment by jhoenicke** [comment]
I uploaded a new maven release.  No idea if the `checkSatAssuming` is now working okay, though.  I guess the proof generation may still be buggy

**Comment by kfriedberger** [comment]
Did you upload the released version to a official Maven repository?
I cannot find a new version via https://mvnrepository.com/search?q=smtinterpol .

**Comment by kfriedberger** [comment]
@jhoenicke any news on that? Maven does not show your release.

**Comment by jhoenicke** [comment]
There is a problem with the build script that it doesn't update the version number :(
So it uploaded it with an old version number and maven probably dropped it.
I removed the file with the old version number and rebuilt and now the version number is okay (`2.5-47-gc0546aa`).

**Comment by kfriedberger** [comment]
Ok, the new version seems to do the job. Thanks.
