### ISSUE TITLE
NullPointerException on Interpolation

### ISSUE THREAD

**Issue by kfriedberger** [ultimate-pa/smtinterpol#38]
The following input causes SMTInterpol (version `2.5-7-g64ec65d` and `2.5-43-gc407d0f`) to fail with a NullPointerException:
<pre>
(set-option :produce-interpolants true)
(set-logic QF_AUFLIRA)
(push 1)
(declare-fun a () Int)
(declare-fun b () Int)
(declare-fun c () Int)
(push 1)
(assert (! (= 1 a) :named term_0))
(assert (! (= a 0) :named term_1))
(assert (! (= b c) :named term_2))
(check-sat)
(get-interpolants term_2)
</pre>

I know that the interpolation query is too short, but this could be checked by SMTInterpol before trying to compute an interpolant. For the given interpolation query I would expect an empty list as result (based on the scheme that N formulas return N-1 interpolants).

An additional question is:
What happens when only some of the asserted formulas are used in the interpolation query?
Is the rest considered as background theory and, e.g., automatically added to each single formula given in the interpolation query? 
For example, can I find some documentation about the result of an intepolation query like `(get-interpolants term_0 term_1)` for the given example? Or is it `undefined behaviour`?

**Comment by jhoenicke** [comment]
Turned out to be a simple typo, so the check if we added a shared symbol, did not check the last partition, which happened to be the only partition in your example.
