### ISSUE TITLE
ClassCastException from check-sat-assuming with annotated term.

### ISSUE THREAD

**Issue by kfriedberger** [ultimate-pa/smtinterpol#48]
The follwing snippet crashes SMTInterpol in revision fca3ef32:
<pre>
(set-option :random-seed 42)
(set-option :produce-proofs true)
(set-logic QF_AUFLIRA)
(declare-fun A () Bool)
(declare-fun pred1 () Bool)
(assert (! (or A pred1) :named term_0))
(check-sat-assuming (pred1))
</pre>

Output:
<pre>
[...]
success
Unexpected Exception: java.lang.ClassCastException: de.uni_freiburg.informatik.ultimate.logic.AnnotatedTerm cannot be cast to de.uni_freiburg.informatik.ultimate.logic.ApplicationTerm
(error "java.lang.ClassCastException: de.uni_freiburg.informatik.ultimate.logic.AnnotatedTerm cannot be cast to de.uni_freiburg.informatik.ultimate.logic.ApplicationTerm")
</pre>

**Comment by tanjaschindler** [comment]
This seems to be fixed by now.

**Comment by kfriedberger** [comment]
@tanjaschindler 
Could you provide a new release for SMTInterpol?
The old release 2.5-479-ga49e50b from the [official website](https://ultimate.informatik.uni-freiburg.de/smtinterpol/download.html) still throws the exception, 
and the releases from [GitHub](https://github.com/ultimate-pa/smtinterpol/releases) are outdated anyway.
