### ISSUE TITLE
NullPointerException 

### ISSUE THREAD

**Issue by numairmansur** [ultimate-pa/smtinterpol#62]
Hi,
For the following file, I get 

```
sat
sat
Unexpected Exception: java.lang.NullPointerException
(error "java.lang.NullPointerException")
```

[nullpointer.smt2](https://github.com/ultimate-pa/smtinterpol/files/4441279/nullpointer.smt2.zip)

commit: 686b1653313351ded0d72450630571a4aceec8ef

**Comment by tanjaschindler** [comment]
@jhoenicke This seems to be the same issue as #60 .
