### ISSUE TITLE
NullPointerException for NRA instances 

### ISSUE THREAD

**Issue by rainoftime** [ultimate-pa/smtinterpol#67]
Related issue: https://github.com/ultimate-pa/smtinterpol/issues/50, where NRA/NIA/LIA instances have been addressed.

------

Hi, for the following formulas

[npd1.txt](https://github.com/ultimate-pa/smtinterpol/files/4454220/npd1.txt)
[npd2.txt](https://github.com/ultimate-pa/smtinterpol/files/4454221/npd2.txt)
[npd3.txt](https://github.com/ultimate-pa/smtinterpol/files/4454222/npd3.txt)

smtinterpol (commit d768667) throws NullPointerException

**Comment by tanjaschindler** [comment]
This should be solved by 5171d77
