### ISSUE TITLE
ClassCastException for UF formula

### ISSUE THREAD

**Issue by rainoftime** [ultimate-pa/smtinterpol#70]
Related and fixed https://github.com/ultimate-pa/smtinterpol/issues/56, https://github.com/ultimate-pa/smtinterpol/issues/68

----

Hi, for the following formula
[cast.txt](https://github.com/ultimate-pa/smtinterpol/files/4478714/cast.txt)

smtinterpol a8a78500ae throws an exception
~~~~
Unexpected Exception: java.lang.ClassCastException: de.uni_freiburg.informatik.ultimate.smtinterpol.theory.cclosure.CCBaseTerm cannot be cast to de.uni_freiburg.informatik.ultimate.smtinterpol.theory.cclosure.CCAppTerm
~~~~

**Comment by jhoenicke** [comment]
Fixed by 81d1978b008146351893fd4f76e0722b4df5f93f
