### ISSUE TITLE
Invalid model for real formulas (QF_UFLRA, QF_NRA, QF_AUFLRA)

### ISSUE THREAD

**Issue by rainoftime** [ultimate-pa/smtinterpol#97]
[model1.txt](https://github.com/ultimate-pa/smtinterpol/files/4639947/model1.txt)
[model2.txt](https://github.com/ultimate-pa/smtinterpol/files/4639948/model2.txt)
[model3.txt](https://github.com/ultimate-pa/smtinterpol/files/4639951/model3.txt)

smtinterpol commit ad60dbab2e
~~~~
...
 FATAL - Model does not satisfy (or (or (>= r2 r1 r2 (/ r1 0.0) r1) (>= r2 r1 r2 (/ r1 0.0) r1) (>= r2 r1 r2 (/ r1 0.0) r1)) (or (>= r2 r1 r2 (/ r1 0.0) r1) (>= r2 r1 r2 (/ r1 0.0) r1) (>= r2 r1 r2 (/ r1 
0.0) r1)))
 FATAL - Model does not satisfy (or (>= r2 r1 r2 (/ r1 0.0) r1) (>= r2 r1 r2 (/ r1 0.0) r1) (>= r2 r1 r2 (/ r1 0.0) r1))
 FATAL - Model does not satisfy (or (or (>= r2 r1 r2 (/ r1 0.0) r1) (>= r2 r1 r2 (/ r1 0.0) r1) (>= r2 r1 r2 (/ r1 0.0) r1)) (or (>= r2 r1 r2 (/ r1 0.0) r1) (>= r2 r1 r2 (/ r1 0.0) r1) (>= r2 r1 r2 (/ r1 
0.0) r1)))
...
~~~~

**Comment by rainoftime** [comment]
Seems relaed to division by zero

**Comment by jhoenicke** [comment]
Yes, we need to remember the values of (/ x 0) in the model and the same for mod and div.   Fix is simple, but ugly.

I'm not sure if it is worth to keep the complication, since we only support linear arithmetic with our own extension of allowing division by constants.  We could just report an error when dividing by 0 occurs in the input and get rid of the code that handles it.

**Comment by jhoenicke** [comment]
There's also the problem how to present the model in case it involves division by zero.  Theoretically the solver should provide the values for (/ x 0) to the user. The standard says it should be done for user-defined symbols.  Maybe something like

```smt2
(define-fun / ((x Real) (y Real)) (ite (and (= x 1.0) (= y 0.0)) 1.0 (/ x y)))
```

**Comment by jhoenicke** [comment]
I decided not to print out any model for division by zero to conform to the standard.
